.TH configuration-generator 1 "January 2009" "configuration-generator 0.1" "User Commands"
.SH NAME
configuration-generator - generate configuration model with given number of options and values per option
.SH SYNOPSIS
configuration-generator NUM_OPTIONS NUM_VALUES
.SH AUTHOR
Written by Can Berk Guder.
.SH COPYRIGHT
Copyright \(co 2009 Can Berk Guder.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
.PP
This is free software: you are free to change and redistribute it. There is NO WARRANTY, to the extent permitted by law.
