.TH table-to-xml 1 "January 2009" "table-to-xml 0.1" "User Commands"
.SH NAME
table-to-xml - convert table from failure-simulator to xml
.SH SYNOPSIS
table-to-xml FAILURE_MODEL TABLE
.SH AUTHOR
Written by Can Berk Guder.
.SH COPYRIGHT
Copyright \(co 2009 Can Berk Guder.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
.PP
This is free software: you are free to change and redistribute it. There is NO WARRANTY, to the extent permitted by law.
