.TH table-to-arff 1 "January 2009" "table-to-arff 0.1" "User Commands"
.SH NAME
table-to-arff - convert table from failure-simulator to arff files
.SH SYNOPSIS
table-to-arff CONFIGURATION_MODEL TABLE TARGET_DIR
.SH AUTHOR
Written by Can Berk Guder.
.SH COPYRIGHT
Copyright \(co 2009 Can Berk Guder.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
.PP
This is free software: you are free to change and redistribute it. There is NO WARRANTY, to the extent permitted by law.
